-- MySQL Script generated by MySQL Workbench
-- Mon Jan 10 11:54:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myabsencemanagementbd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myabsencemanagementbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myabsencemanagementbd` DEFAULT CHARACTER SET utf8 ;
USE `myabsencemanagementbd` ;

-- -----------------------------------------------------
-- Table `myabsencemanagementbd`.`Annee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myabsencemanagementbd`.`Annee` (
  `idAnnee` INT NOT NULL,
  PRIMARY KEY (`idAnnee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myabsencemanagementbd`.`Niveau`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myabsencemanagementbd`.`Niveau` (
  `nomNiveau` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`nomNiveau`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `myabsencemanagementbd`.`Etudiants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myabsencemanagementbd`.`Etudiants` (
  `matriculeEt` VARCHAR(15) NOT NULL,
  `nomEtudiant` VARCHAR(45) NULL,
  `prenomEtudiant` VARCHAR(45) NULL,
  `dateDeNaissance` DATE NULL,
  `Annee_idAnnee` INT NOT NULL,
  `Niveau_nomNiveau` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`matriculeEt`, `Annee_idAnnee`, `Niveau_nomNiveau`),
  INDEX `fk_Etudiants_Annee_idx` (`Annee_idAnnee` ASC) VISIBLE,
  INDEX `fk_Etudiants_Niveau1_idx` (`Niveau_nomNiveau` ASC) VISIBLE,
  CONSTRAINT `fk_Etudiants_Annee`
    FOREIGN KEY (`Annee_idAnnee`)
    REFERENCES `myabsencemanagementbd`.`Annee` (`idAnnee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Etudiants_Niveau1`
    FOREIGN KEY (`Niveau_nomNiveau`)
    REFERENCES `myabsencemanagementbd`.`Niveau` (`nomNiveau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myabsencemanagementbd`.`Date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myabsencemanagementbd`.`Date` (
  `idDate` INT NOT NULL AUTO_INCREMENT,
  `dateAbsence` DATE NULL,
  PRIMARY KEY (`idDate`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myabsencemanagementbd`.`Ues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myabsencemanagementbd`.`Ues` (
  `codeUe` VARCHAR(15) NOT NULL,
  `intitule` VARCHAR(100) NULL,
  `credit` INT NULL,
  `semestre` INT NULL,
  `Niveau_nomNiveau` VARCHAR(15) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`codeUe`, `Niveau_nomNiveau`),
  INDEX `fk_Ues_Niveau1_idx` (`Niveau_nomNiveau` ASC) VISIBLE,
  CONSTRAINT `fk_Ues_Niveau1`
    FOREIGN KEY (`Niveau_nomNiveau`)
    REFERENCES `myabsencemanagementbd`.`Niveau` (`nomNiveau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myabsencemanagementbd`.`Absenter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myabsencemanagementbd`.`Absenter` (
  `Etudiants_matriculeEt` VARCHAR(15) NOT NULL,
  `Etudiants_Annee_idAnnee` INT NOT NULL,
  `Etudiants_Niveau_nomNiveau` VARCHAR(15) NOT NULL,
  `Ues_codeUe` VARCHAR(15) NOT NULL,
  `Ues_Niveau_nomNiveau` VARCHAR(15) NOT NULL,
  `Date_idDate` INT NOT NULL,
  `duree` INT NULL,
  PRIMARY KEY (`Etudiants_matriculeEt`, `Etudiants_Annee_idAnnee`, `Etudiants_Niveau_nomNiveau`, `Ues_codeUe`, `Ues_Niveau_nomNiveau`, `Date_idDate`),
  INDEX `fk_Etudiants_has_Ues_Ues1_idx` (`Ues_codeUe` ASC, `Ues_Niveau_nomNiveau` ASC) VISIBLE,
  INDEX `fk_Etudiants_has_Ues_Etudiants1_idx` (`Etudiants_matriculeEt` ASC, `Etudiants_Annee_idAnnee` ASC, `Etudiants_Niveau_nomNiveau` ASC) VISIBLE,
  INDEX `fk_Etudiants_has_Ues_Date1_idx` (`Date_idDate` ASC) VISIBLE,
  CONSTRAINT `fk_Etudiants_has_Ues_Etudiants1`
    FOREIGN KEY (`Etudiants_matriculeEt` , `Etudiants_Annee_idAnnee` , `Etudiants_Niveau_nomNiveau`)
    REFERENCES `myabsencemanagementbd`.`Etudiants` (`matriculeEt` , `Annee_idAnnee` , `Niveau_nomNiveau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Etudiants_has_Ues_Ues1`
    FOREIGN KEY (`Ues_codeUe` , `Ues_Niveau_nomNiveau`)
    REFERENCES `myabsencemanagementbd`.`Ues` (`codeUe` , `Niveau_nomNiveau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Etudiants_has_Ues_Date1`
    FOREIGN KEY (`Date_idDate`)
    REFERENCES `myabsencemanagementbd`.`Date` (`idDate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myabsencemanagementbd`.`Noter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myabsencemanagementbd`.`Noter` (
  `Etudiants_matriculeEt` VARCHAR(15) NOT NULL,
  `Etudiants_Annee_idAnnee` INT NOT NULL,
  `Etudiants_Niveau_nomNiveau` VARCHAR(15) NOT NULL,
  `Ues_codeUe` VARCHAR(15) NOT NULL,
  `Ues_Niveau_nomNiveau` VARCHAR(15) NOT NULL,
  `noteCC` DOUBLE NULL,
  `noteSN` DOUBLE NULL,
  `ifTP` INT NULL,
  `noteTP` DOUBLE NULL,
  PRIMARY KEY (`Etudiants_matriculeEt`, `Etudiants_Annee_idAnnee`, `Etudiants_Niveau_nomNiveau`, `Ues_codeUe`, `Ues_Niveau_nomNiveau`),
  INDEX `fk_Etudiants_has_Ues_Ues2_idx` (`Ues_codeUe` ASC, `Ues_Niveau_nomNiveau` ASC) VISIBLE,
  INDEX `fk_Etudiants_has_Ues_Etudiants2_idx` (`Etudiants_matriculeEt` ASC, `Etudiants_Annee_idAnnee` ASC, `Etudiants_Niveau_nomNiveau` ASC) VISIBLE,
  CONSTRAINT `fk_Etudiants_has_Ues_Etudiants2`
    FOREIGN KEY (`Etudiants_matriculeEt` , `Etudiants_Annee_idAnnee` , `Etudiants_Niveau_nomNiveau`)
    REFERENCES `myabsencemanagementbd`.`Etudiants` (`matriculeEt` , `Annee_idAnnee` , `Niveau_nomNiveau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Etudiants_has_Ues_Ues2`
    FOREIGN KEY (`Ues_codeUe` , `Ues_Niveau_nomNiveau`)
    REFERENCES `myabsencemanagementbd`.`Ues` (`codeUe` , `Niveau_nomNiveau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myabsencemanagementbd`.`Resultats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myabsencemanagementbd`.`Resultats` (
  `idResultats` INT NOT NULL AUTO_INCREMENT,
  `mgp` DOUBLE NULL,
  `Etudiants_matriculeEt` VARCHAR(15) NOT NULL,
  `Etudiants_Annee_idAnnee` INT NOT NULL,
  `Etudiants_Niveau_nomNiveau` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idResultats`, `Etudiants_matriculeEt`, `Etudiants_Annee_idAnnee`, `Etudiants_Niveau_nomNiveau`),
  INDEX `fk_Resultats_Etudiants1_idx` (`Etudiants_matriculeEt` ASC, `Etudiants_Annee_idAnnee` ASC, `Etudiants_Niveau_nomNiveau` ASC) VISIBLE,
  CONSTRAINT `fk_Resultats_Etudiants1`
    FOREIGN KEY (`Etudiants_matriculeEt` , `Etudiants_Annee_idAnnee` , `Etudiants_Niveau_nomNiveau`)
    REFERENCES `myabsencemanagementbd`.`Etudiants` (`matriculeEt` , `Annee_idAnnee` , `Niveau_nomNiveau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `myabsencemanagementbd`.`notifications`
-- -----------------------------------------------------
CREATE TABLE `myabsencemanagementbd`.`notifications` ( `id` INT NOT NULL AUTO_INCREMENT , `message_a_noctifier` VARCHAR(255) NOT NULL , `date` DATE NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `myabsencemanagementbd`.`messages`
-- -----------------------------------------------------
CREATE TABLE `myabsencemanagementbd`.`messages`( 
  `id` INT NOT NULL AUTO_INCREMENT ,
  `nom` VARCHAR(255) NOT NULL , 
  `email` VARCHAR(255) NOT NULL , 
  `telephone` VARCHAR(255) NOT NULL , 
  `message` TEXT NOT NULL , 
  PRIMARY KEY (`id`)) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
